/**
 * Типы мутаций
 */
export const GOT_PROJECTS = 'GOT_PROJECTS'
export const GOT_PROJECTS_REQUEST_PROCESSING = 'GOT_PROJECTS_REQUEST_PROCESSING'
export const GOT_PROJECTS_REQUEST_COMPLETION = 'GOT_PROJECTS_REQUEST_COMPLETION'

export const GOT_PROJECT = 'GOT_PROJECT'
export const GOT_PROJECT_REQUEST_PROCESSING = 'GOT_PROJECT_REQUEST_PROCESSING'
export const GOT_PROJECT_REQUEST_COMPLETION = 'GOT_PROJECT_REQUEST_COMPLETION'

export const GOT_PROJECT_SELECTED = 'GOT_PROJECT_SELECTED'
export const GOT_PROJECT_CREATED = 'GOT_PROJECT_CREATED'
export const GOT_PROJECT_UPDATED = 'GOT_PROJECT_UPDATED'
export const GOT_PROJECT_DELETED = 'GOT_PROJECT_DELETED'

export const GOT_PROJECT_TABLE_STATISTIC = 'GOT_PROJECT_TABLE_STATISTIC'
export const GOT_PROJECT_CHART_STATISTIC = 'GOT_PROJECT_CHART_STATISTIC'

export default {
  GOT_PROJECTS,
  GOT_PROJECTS_REQUEST_PROCESSING,
  GOT_PROJECTS_REQUEST_COMPLETION,

  GOT_PROJECT,
  GOT_PROJECT_REQUEST_PROCESSING,
  GOT_PROJECT_REQUEST_COMPLETION,

  GOT_PROJECT_CREATED,
  GOT_PROJECT_UPDATED,
  GOT_PROJECT_DELETED,
  GOT_PROJECT_SELECTED,

  GOT_PROJECT_TABLE_STATISTIC,
  GOT_PROJECT_CHART_STATISTIC,
}
